Release 202510262254.13

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -1,32 +1,43 @@
 DIR=`pwd`
-PROJECT=`basename $DIR`
-REL=`parse-setup-version.py`
+PROJECT_DIR=`basename $DIR`
+PROJECT="`echo $PROJECT_DIR | tr '-' '_'`"
+
+REL="`parse-pyproject-version.py --patch`"
+if [ "$?" != "0" ]; then
+    REL=""
+fi
+if [ -z "$1" ] && [ "$REL" == "" ]; then
+    echo "Usage: <release version>"
+    exit 1
+fi
+if [ -z "$REL" ]; then
+    REL="$1"
+fi
+
 echo "Making release $REL of $PROJECT"
 
-rm -rf dist
-rm -rf htmlcov
-python3 setup.py sdist
+rm -rf dist htmlcov buyild MANIFEST *.egg-info
+./venv/bin/python -m build
+if [ "$?" != "0" ]; then
+    echo "ERROR: ./venv/bin/python -m build failed, exiting"
+    exit
+fi
 
-# clean venv/ directory from the dist
-# TODO: cleaner way to do this (using setup.py/MANIFEST.in)
+# clean venv/ and htmlcov/ directories from the dist
 cd dist
 FILE="$PROJECT-$REL"
 echo $FILE
-cd dist
 tar xvf "$FILE.tar.gz"
-rm -f "$FILE/.covera*"
-rm -f "$FILE/coverage.xml"
-rm -rf "$FIR/.mypy_cache"
-rm -rf "$FILE/venv"
-rm -rf "$FILE/data"
-rm -rf "$FILE/linecalc.conf"
-rm -rf "$FILE/uploads"
-rm -rf "$FILE/.idea"
+for DIR_TO_BE_DELETED in venv uploads downloads certs .idea coverage.xml project logs .mypy_cache linecalc.conf mypy.ini pyproject.toml requirements-dev.txt; do
+    rm -rf "$FILE/$DIR_TO_BE_DELETED"
+done
 find . -name "__pycache__" -type d -exec rm -r "{}" \;
 rm "$FILE.tar.gz"
+rm "*.whl"
 tar zcvf "$FILE.tar.gz" $FILE
 rm -rf $FILE
 cd ..
 
-twine upload dist/$FILE.tar.gz
-
+if [ "$1" != "--no-upload" ]; then
+    twine upload dist/$FILE.tar.gz
+fi
